spring.application.name=ms-eureka
server.port=8761

# Como este componente es el servidor, le indicamos que no se registre a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false