spring.application.name=ms-adopciones
server.port=8085

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/db_adopciones
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

usuario-service.url=http://${USUARIO_HOST:localhost}:8081/api/usuarios
refugio-service.url=http://${REFUGIO_HOST:localhost}:8084/api/refugios
mascota-service.url=http://${MASCOTA_HOST:localhost}:8086/api/mascotas

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
