spring.application.name=ms-gateway
server.port=8080

# Registro en el directorio de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ═══════════════════════════════════════════════════
# CONFIGURACIÓN DE ENRUTAMIENTO (SPRING CLOUD GATEWAY)
# ═══════════════════════════════════════════════════

# 1. Ruta para el Microservicio de Usuarios
spring.cloud.gateway.routes[0].id=ms-usuarios
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# 2. Ruta para el Microservicio de Autenticación
spring.cloud.gateway.routes[1].id=ms-autenticacion
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**

# 3. Ruta para el Microservicio de Refugios
spring.cloud.gateway.routes[2].id=ms-refugios
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/refugios/**

# 4. Ruta para el Microservicio de Mascotas
spring.cloud.gateway.routes[3].id=ms-mascotas
spring.cloud.gateway.routes[3].uri=http://localhost:8086
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/mascotas/**

# 5. Ruta para el Microservicio de Adopciones
spring.cloud.gateway.routes[4].id=ms-adopciones
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/adopciones/**

# 6. Ruta para el Microservicio de Reportes (Mascotas Perdidas)
spring.cloud.gateway.routes[5].id=ms-reportes
spring.cloud.gateway.routes[5].uri=http://localhost:8087
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/reportes/**

# 7. Ruta para el Microservicio de Publicaciones (Marketplace)
spring.cloud.gateway.routes[6].id=ms-publicaciones
spring.cloud.gateway.routes[6].uri=http://localhost:8088
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/publicaciones/**

# 8. Ruta para el Microservicio de Pedidos (Compras Marketplace)
spring.cloud.gateway.routes[7].id=ms-pedidos
spring.cloud.gateway.routes[7].uri=http://localhost:8089
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/pedidos/**