spring.application.name=ms-publicaciones
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/db_publicaciones
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URL base para WebClient (comunicación con ms-usuarios)
usuario-service.url=http://localhost:8081/api/usuarios